name: Deploy

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo "TERM=linux" >> "$GITHUB_ENV"

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Checking out all submodules to the tip of a branch
      run: git submodule foreach --recursive git checkout main

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23'
        check-latest: true

    - name: Set up 7-zip
      uses: milliewalky/setup-7-zip@v2

    - name: Build
      run: make
