name: Release

on:
  workflow_dispatch:

jobs:
  BuildAndRelease:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo "TERM=linux" >> "$GITHUB_ENV"

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Checking out all submodules to the tip of a branch
      run: git submodule foreach --recursive git checkout main

    - name: Version number
      run: echo "MT_VERSION=2.0.2-beta" >> "$GITHUB_ENV"

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23'
        check-latest: true

    - name: Set up 7-zip
      uses: milliewalky/setup-7-zip@v2

    - name: Build binaries
      run: make

    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        tag_name: $MT_VERSION
        make_latest: true
        files: |
          dist/mt-checklist-{{$MT_VERSION}}-linux32.7z
          dist/mt-checklist-{{$MT_VERSION}}-linux64.7z
          dist/mt-checklist-{{$MT_VERSION}}-win32.7z
          dist/mt-checklist-{{$GITHUB_REF_NAME}}-win64.7z
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
